---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "house"
spec:
  configuration:
    users:
      test/password: qwerty
      test/networks/ip:
        - "0.0.0.0/0"
      test/grants/query:
        - "GRANT SHOW ON *.*"
        - "GRANT CREATE ON *.* WITH GRANT OPTION"
        - "GRANT SELECT ON system.*"
    zookeeper:
      nodes:
        - host: chk-0.zookeeper.olap
          port: 2181
        - host: chk-1.zookeeper.olap
          port: 2181
        - host: chk-2.zookeeper.olap
          port: 2181
    clusters:
      - name: replicated
        templates:
          podTemplate: pod-template-with-volumes
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.3.8.21
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server
    volumeClaimTemplates:
      - name: data-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
      - name: log-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
