apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector-kafka
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  config: |
    receivers:
      fluentforward:
        endpoint: 0.0.0.0:24224
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      # batch:
      #   send_batch_size: 100000
      #   timeout: 5s
      memory_limiter:
        check_interval: 2s
        limit_mib: 1800
        spike_limit_mib: 500
      resourcedetection/system:
        detectors: [ "system" ]
        system:
          hostname_sources: [ "os" ]
      resource:
        attributes:
          - key: service.name
            value: "upsertedServiceName"
            action: upsert
    exporters:
      kafka:
        brokers:
          - teeth-queue-kafka-brokers.kafka.svc.cluster.local:9092
        encoding: otlp_json
    extensions:
      health_check:
      pprof:
      zpages:
      memory_ballast:
        size_mib: 1000
      basicauth/client:
        client_auth:
          username: admin
          password: admin
    service:
      extensions: [ pprof, zpages, health_check ]
      pipelines:
        logs:
          receivers: [ fluentforward, otlp ]
          processors: [ memory_limiter, resourcedetection/system, resource ]
          exporters: [ kafka ]
        # traces:
        #   receivers: [ otlp ]
        #   processors: [ memory_limiter, resourcedetection/system, resource ]
        #   exporters: [ kafka ]
