apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-teeth-search-monitor
  labels:
    opster.io/opensearch-cluster: teeth-search
    release: my-monitoring
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: teeth-search-admin-password
      username:
        key: username
        name: teeth-search-admin-password
    bearerTokenSecret:
      key: ""
    interval: 30s
    path: /_prometheus/metrics
    port: http
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: my-teeth-search-monitor
  podTargetLabels:
  - opster.io/opensearch-cluster
  selector:
    matchLabels:
      opster.io/opensearch-cluster: teeth-search
  targetLabels:
  - opster.io/opensearch-cluster
