apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: teeth-search
  namespace: default
spec:
  general:
    serviceName: teeth-search
    version: 2.8.0
    # setVMMaxMapCount: true
    monitoring:
      enable: true
      scrapeInterval: 30s
      pluginUrl: https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.8.0.0/prometheus-exporter-2.8.0.0.zip
  dashboards:
    enable: true
    version: 2.8.0
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "5Gi"
      nodeSelector:
      resources:
        requests:
            memory: "2Gi"
            cpu: "500m"
        limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
    - component: master
      replicas: 3
      diskSize: "1Gi"
      nodeSelector:
      resources:
        requests:
            memory: "2Gi"
            cpu: "500m"
        limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "cluster_manager"
