apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-credentials
    namespace: olap
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:HpzFj3eP,iv:hOGOz3+D9Q2tsln3D/BNWraKkV6649PxmA/p3KuHHvA=,tag:YOsb7Hz/2k8FnUs64VWQ1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV0tRVCszOWxTS0hSdHQ1
            RVBMR0FVbkxXczhGYmdKSFhSbkVWRWFwanhNCnloRDlvcm16cU1VTWdIQUVCY2Jp
            Zm1sTXZRT0NUM3VXc3ZnbUhWYVdsQVEKLS0tIDVXODlhWGV6TjJKemU4N3Q1T3E1
            ZFdWeUxjaXdIS2hISnZDTk56K0JlcTQKjLlgaHQyW7bRiy6okBj84fsfVYs9TJNG
            ncib8CHxm/jomZPe2aHrwXEeDlyG6BvMyYCubrm6L+gedkYj9WCvog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age176qtdr0s05kneh5dejm4u849x3ttrlct3ah2775n7vnykyruj4kqwxavxz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T04:27:30Z"
    mac: ENC[AES256_GCM,data:RYTejw5Q2+FFO2GAuya9W02BOvrugn2pz7w9qfOF+O4dRXBWgvAFyvZm71bauMkE1pcSZgy4DI14aYjJ+sNtFqerIaj0RkuAYEGTWKXT3TD0uDn4V+KF/aH27WEzZuRoRwns6a3cZ9VYfRXaOJfXwjpnAJJJqC+nCTMDlbxZB24=,iv:lZzGETexTbRgKxzdOxO91zzlao3J85Mb/bMEHhGkrZQ=,tag:UXYWDBEpfCa0wDMyQpk8Og==,type:str]
    version: 3.13.1
