apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-credentials
    namespace: olap
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:HpzFj3eP,iv:hOGOz3+D9Q2tsln3D/BNWraKkV6649PxmA/p3KuHHvA=,tag:YOsb7Hz/2k8FnUs64VWQ1g==,type:str]
    otel_writer_password: ENC[AES256_GCM,data:vbPLPvKT0oC7+0sVlf2FSQMxe/Zqz84cidCG94gfYQQ=,iv:QTqPlGwT7/jMZlEuhEPnhQKsKwmhuM+qYIXfMYxHHLU=,tag:G/o5EkAQ9s2StuKSOcwDAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV0tRVCszOWxTS0hSdHQ1
            RVBMR0FVbkxXczhGYmdKSFhSbkVWRWFwanhNCnloRDlvcm16cU1VTWdIQUVCY2Jp
            Zm1sTXZRT0NUM3VXc3ZnbUhWYVdsQVEKLS0tIDVXODlhWGV6TjJKemU4N3Q1T3E1
            ZFdWeUxjaXdIS2hISnZDTk56K0JlcTQKjLlgaHQyW7bRiy6okBj84fsfVYs9TJNG
            ncib8CHxm/jomZPe2aHrwXEeDlyG6BvMyYCubrm6L+gedkYj9WCvog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age176qtdr0s05kneh5dejm4u849x3ttrlct3ah2775n7vnykyruj4kqwxavxz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T20:55:22Z"
    mac: ENC[AES256_GCM,data:w2Cf8KS6uzwFfapeLokor1NY4VCQ4dj49QmPenDFa+/TJeci7HWl2HKUw9YzcqoMhbPKm+DrBb08GPUj7o3++0pPhtVTUYImhUMopW/fLLD5H6uzYhqjm6v9PnODzNmLtHyQIObK++ez9T1WS/7hIoRy1ujE06/4lA2EXAm91U8=,iv:/z+FqVAkNXwR6v5XM/djsqp6KIsmYorsukrW10TaMW4=,tag:OCk7kRkceaeT7PWyMbKOqQ==,type:str]
    version: 3.13.1
