apiVersion: v1
kind: Pod
metadata:
  name: vector-kafka-consumer
  namespace: kafka
  labels:
    app: vector-kafka-consumer
spec:
  restartPolicy: Never
  containers:
  - name: vector
    image: timberio/vector:0.34.0-debian
    command: [ "/bin/bash" ]
    args: [ "-c", "vector --config /etc/vector/vector.yaml" ]
    volumeMounts:
    - name: vector-config
      mountPath: /etc/vector
    env:
    - name: VECTOR_LOG
      value: "info"
    - name: RUST_LOG
      value: "info"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  volumes:
  - name: vector-config
    configMap:
      name: vector-config
