apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector-datadog
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  env:
  - name: OTEL_LOG_LEVEL
    value: "debug"
  - name: DATADOG_API_KEY
    valueFrom:
      secretKeyRef:
        name: datadog-api-key
        key: api-key
  config: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "localhost:4318"
          grpc:
            endpoint: "localhost:4317"
      hostmetrics:
        collection_interval: 10s
        scrapers:
          paging:
            metrics:
              system.paging.utilization:
                enabled: true
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
          disk:
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
          load:
          memory:
          network:
          processes:
    exporters:
      datadog/exporter:
        api:
          site: "us5.datadoghq.com"
          key: "${env:DATADOG_API_KEY}"
    connectors:
      datadog/connector:
    processors:
      batch:
        send_batch_max_size: 100
        send_batch_size: 10
        timeout: 10s
    service:
      pipelines:
        metrics:
          receivers: [ datadog/connector, otlp, hostmetrics ]
          processors: [ batch ]
          exporters: [ datadog/exporter ]
        traces:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ datadog/connector, datadog/exporter ]
        logs:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ datadog/exporter ]
